CREATE DATABASE site;
USE site

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	principal BOOLEAN DEFAULT 0,
	preco FLOAT(10,2) NOT NULL,
	descricao VARCHAR(100),
	desconto FLOAT(5,2) DEFAULT 0,
	nome  VARCHAR(50) NOT NULL,
	estoque INT NOT NULL,
	img VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUTO_CATEGORIAS(
	ID_PRODUTO INT NOT NULL,
	ID_CATEGORIAS INT NOT NULL
);

CREATE TABLE CATEGORIAS(
	IDCATEGORIAS INT PRIMARY KEY AUTO_INCREMENT,
	categoria VARCHAR(30) NOT NULL
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	CPF CHAR(11) NOT NULL,
	ID_ENDERECO INT NOT NULL,
	ID_TELEFONE INT NOT NULL,
	senha VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	numero INT,
	CEP VARCHAR(10) NOT NULL,
	bairro VARCHAR(30) NOT NULL,
	cidade VARCHAR(30) NOT NULL,
	estado CHAR(2) NOT NULL,
	complemento VARCHAR(50)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	ddd CHAR(3) NOT NULL,
	numero VARCHAR(10) NOT NULL
);

CREATE TABLE ITEM(
	IDITEM INT PRIMARY KEY AUTO_INCREMENT,
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	quantidade INT DEFAULT 0
);

CREATE TABLE VENDAS(
	IDVENDAS INT PRIMARY KEY AUTO_INCREMENT,
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	quantidade INT NOT NULL,
	time DATETIME NOT NULL,
	preco FLOAT(10,2) NOT NULL
);

ALTER TABLE PRODUTO_CATEGORIAS ADD CONSTRAINT 
PK_PRODUTO_CATEGORIAS PRIMARY KEY(ID_PRODUTO,ID_CATEGORIAS);

ALTER TABLE PRODUTO_CATEGORIAS ADD CONSTRAINT FK_PC_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO);

ALTER TABLE PRODUTO_CATEGORIAS ADD CONSTRAINT FK_PC_CATEGORIAS
FOREIGN KEY(ID_CATEGORIAS) REFERENCES CATEGORIAS(IDCATEGORIAS);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIAS
FOREIGN KEY(ID_CATEGORIAS) REFERENCES CATEGORIAS(IDCATEGORIAS);

ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO);

ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_CLIENTE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_ENDERECO
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(IDENDERECO);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_TELEFONE) REFERENCES TELEFONE(IDTELEFONE);

ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO);

ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_CLIENTE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

DELIMITER $
CREATE TRIGGER SAVE_ADM
BEFORE DELETE ON ITEM
FOR EACH ROW
BEGIN

	INSERT INTO VENDAS VALUES (NULL,OLD.ID_PRODUTO, 
	OLD.ID_CLIENTE, OLD.quantidade, (SELECT NOW() AS time), 
	(SELECT P.preco FROM PRODUTO AS P WHERE P.IDPRODUTO=OLD.ID_PRODUTO));
	
END
$
DELIMITER ;

CREATE VIEW DADOS AS
SELECT C.IDCLIENTE, C.nome, C.email, E.nome AS longradura, E.numero, E.CEP, E.bairro, 
E.cidade, E.estado, E.complemento, T.ddd,T.numero AS telefone 
FROM CLIENTE AS C 
INNER JOIN ENDERECO AS E ON C.ID_ENDERECO=E.IDENDERECO 
INNER JOIN TELEFONE AS T ON C.ID_TELEFONE=T.IDTELEFONE;

INSERT INTO CATEGORIAS (categoria) VALUES ('fruta'),('aleatorio'),('escolar'),('beleza'),('utensilios');

INSERT INTO PRODUTO (principal,preco,descricao,desconto,nome,estoque,img) VALUES
                    (1,       9.5,'Romã boa',    0,    'Romã', 60, 'roma'),
                    (0,       6, 'Pera boa',     5,    'Pera', 85, 'pera'),
                    (0,      75, 'Pedra rosa',   0,    'Pedra',50,'pedra1'),
                    (0,      6, 'Limão siciliano bom',   10, 'Limão siciliano',45,'limao'),
                    (1,     20,'Lapiseira cinza',0,'Lapiseira',100,'lapiseira'),
                    (1,     45,'Faca amolada',   0,'Faca',     75,'faca'),
                    (0,     7,'Cebola boa',      0,'Cebola',   55,'cebola'),
                    (0,    25,'produto beleza',  0,'Beleza',   25,'beleza'),
                    (0,    12,'Abacaxi bom',     0,'Abacaxi',  60,'abacaxi');

INSERT INTO PRODUTO_CATEGORIAS (ID_PRODUTO,ID_CATEGORIAS) VALUES
(1,1), (2,1) , (3,2) , (4,1) , (5,3), (6,5) , (7,1) , (8,4) , (9,1);