USE site

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	preco FLOAT(10,2) NOT NULL,
	descricao VARCHAR(100),
	desconto INT DEFAULT 0,
	nome  VARCHAR(50) NOT NULL,
	estoque INT NOT NULL
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	CPF CHAR(11) NOT NULL,
	ID_ENDERECO INT NOT NULL,
	ID_TELEFONE INT NOT NULL,
	senha VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	numero INT,
	CEP VARCHAR(10) NOT NULL,
	bairro VARCHAR(30) NOT NULL,
	cidade VARCHAR(30) NOT NULL,
	estado CHAR(2) NOT NULL,
	complemento VARCHAR(50)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	ddd CHAR(3) NOT NULL,
	numero VARCHAR(10) NOT NULL
);

CREATE TABLE ITEM(
	IDITEM INT PRIMARY KEY AUTO_INCREMENT,
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	quantidade INT DEFAULT 0
);

CREATE TABLE VENDAS(
	IDVENDAS INT PRIMARY KEY AUTO_INCREMENT,
	ID_PRODUTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	quantidade INT NOT NULL,
	time DATETIME NOT NULL,
	preco FLOAT(10,2) NOT NULL
);

ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO);

ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_CLIENTE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_ENDERECO
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(IDENDERECO);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_TELEFONE) REFERENCES TELEFONE(IDTELEFONE);

ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO);

ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_CLIENTE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);


DELIMITER $
CREATE TRIGGER SAVE_ADM
BEFORE DELETE ON ITEM
FOR EACH ROW
BEGIN

	INSERT INTO VENDAS VALUES (NULL,OLD.ID_PRODUTO, 
	OLD.ID_CLIENTE, OLD.quantidade, (SELECT NOW() AS time), 
	(SELECT P.preco FROM PRODUTO AS P WHERE P.IDPRODUTO=OLD.ID_PRODUTO));
	
END
$
DELIMITER ;